sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null; #Download and install Google SDK on travis env
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl #install & upd kubectl on travis env
  - gcloud auth activate-service-account --key-file service-account.json #auth on GC
  - gcloud config set project multi-k8s-309708 #GC project to bind to
  - gcloud config set compute/zone europe-north1-a #GC cluster location
  - gcloud container clusters get-credentials multi-cluster #GC cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t ilonaosv/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ilonaosv/react-test npm test
